export const LS_CACHE_KEY = 'LS_CACHE_KEY';
export const LS_ACCESS_TOKEN_KEY = 'LS_ACCESS_TOKEN_KEY';
export const LS_USER_STORE_KEY = 'LS_USER_STORE_KEY';

export const API_LOGIN = 'API_LOGIN';
export const API_REGISTER = 'API_REGISTER';
export const API_DICTIONARY_CHARACTERS = 'API_DICTIONARY_CHARACTERS';
export const API_LEADERBOARD = 'API_MATCH_HISTORY';
export const API_PLAYERS = 'API_PLAYERS';
export const API_PROFILE_INFO = 'API_PROFILE_INFO';
export const API_MATCH_HISTORY = 'API_MATCH_HISTORY';
export const API_DICTIONARY_USERNAMES = 'API_DICTIONARY_USERNAMES';
export const API_CREATE_CHALLENGE = 'API_CREATE_CHALLENGE';
export const API_GET_CHALLENGES = 'API_GET_CHALLENGES';
export const API_GET_CHALLENGE = 'API_GET_CHALLENGE';
export const API_CHANGE_CHALLENGE_STATUS = 'API_CHANGE_CHALLENGE_STATUS';
export const API_EDIT_PROFILE = "API_EDIT_PROFILE";
export const API_CHANGE_PASSWORD = "API_CHANGE_PASSWORD";
export const API_GET_MATCH = "API_GET_MATCH";
export const API_DECLINE_MATCH = "API_DECLINE_MATCH";
export const API_MATCH_SUBMIT_SCORE = "API_MATCH_SUBMIT_SCORE";
export const API_CHANGE_SCORE_CONFIRMATION = "API_CHANGE_SCORE_CONFIRMATION";

export const MATCH_HISTORY_HIDE_COLUMNS: {
	CATEGORY: "CATEGORY",
	FIRST_TO: "FIRST_TO",
	DELTA: "DELTA",
	SCORE: "SCORE"
} = {
	CATEGORY: "CATEGORY",
	FIRST_TO: "FIRST_TO",
	DELTA: "DELTA",
	SCORE: "SCORE"
};

export const MY_CHALLENGES_HIDE_COLUMNS: {

	FIRST_TO: "FIRST_TO",
	STATUS: "STATUS"
} = {
	FIRST_TO: "FIRST_TO",
	STATUS: "STATUS"
};